### ISSUE TITLE
set scope for /authorize by default

### ISSUE THREAD

**Issue by ceralena** [greensync/omniauth-dex-energy#10]
In greensync/who#183, we discovered that our clients aren't setting the "scope" parameter. I suggest that we update the strategy such that `authorize_params` includes `scope: 'openid'` by default.

**Comment by ceralena** [comment]
While fixing greensync/who#183, I actually realized that scope is optional - so let's just leave it.

**Comment by nickburgin** [comment]
It's not optional in the Open ID spec: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

**Comment by ceralena** [comment]
re-opening this per the above comment; let's add it!
